name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: setup-bun
        name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - id: install-deps
        name: Install dependencies
        run: |
          bun install
      - id: build
        name: Run build
        run: |
          bun run build
      - id: test
        name: Run test
        run: |
          bun run test
